host: 127.0.0.1:8000
info:
  contact:
    email: Piwriw@163.com
    name: Piwriw
    url: https://github.com/Piwriw
  description: Go web边缘计算管理平台项目接口文档
  title: 边缘计算管理平台项目接口文档
  version: "1.0"
paths:
  /:namespace/:name/:
    post:
      consumes:
      - application/json
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        type: string
      produces:
      - application/json
      responses: {}
      security:
      - ApiKeyAuth: []
      summary: Delete Pod接口
      tags:
      - Pod相关接口
  /ai_model/ai_model/:
    get:
      consumes:
      - application/json
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        type: string
      produces:
      - application/json
      responses: {}
      security:
      - ApiKeyAuth: []
      summary: Get AIModel 接口
      tags:
      - AIModel  相关接口
    post:
      consumes:
      - application/json
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        type: string
      produces:
      - application/json
      responses: {}
      security:
      - ApiKeyAuth: []
      summary: Post AIModel 接口
      tags:
      - AIModel  相关接口
  /device/device/:
    post:
      consumes:
      - application/json
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        type: string
      produces:
      - application/json
      responses: {}
      security:
      - ApiKeyAuth: []
      summary: Post Device 详情接口
      tags:
      - Device  相关接口
  /device/device/default/:name/:
    get:
      consumes:
      - application/json
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        type: string
      produces:
      - application/json
      responses: {}
      security:
      - ApiKeyAuth: []
      summary: GET Device 详情接口
      tags:
      - Device  相关接口
  /device/devicemodel/:
    delete:
      consumes:
      - application/json
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        type: string
      produces:
      - application/json
      responses: {}
      security:
      - ApiKeyAuth: []
      summary: DELETE Device Model详情接口
      tags:
      - Device Model 相关接口
    get:
      consumes:
      - application/json
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        type: string
      produces:
      - application/json
      responses: {}
      security:
      - ApiKeyAuth: []
      summary: Get Device Model详情接口
      tags:
      - Device Model详情相关接口
    post:
      consumes:
      - application/json
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        type: string
      produces:
      - application/json
      responses: {}
      security:
      - ApiKeyAuth: []
      summary: Get Device Model详情接口
      tags:
      - Device Model详情相关接口
    put:
      consumes:
      - application/json
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        type: string
      produces:
      - application/json
      responses: {}
      security:
      - ApiKeyAuth: []
      summary: Update Device Model详情接口
      tags:
      - Device Model 相关接口
  /device/devicemodel/default/:name/:
    get:
      consumes:
      - application/json
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        type: string
      produces:
      - application/json
      responses: {}
      security:
      - ApiKeyAuth: []
      summary: Get Device Model详情接口
      tags:
      - Device Model详情相关接口
  /node/join/:
    get:
      consumes:
      - application/json
      description: 获取Node信息
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        type: string
      produces:
      - application/json
      responses: {}
      security:
      - ApiKeyAuth: []
      summary: 获取Node接口
      tags:
      - Node相关接口
  /node/label/:
    post:
      consumes:
      - application/json
      description: Delete Node信息
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        type: string
      produces:
      - application/json
      responses: {}
      security:
      - ApiKeyAuth: []
      summary: Delete Node接口
      tags:
      - Node相关接口
    put:
      consumes:
      - application/json
      description: 获取Node信息
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        type: string
      produces:
      - application/json
      responses: {}
      security:
      - ApiKeyAuth: []
      summary: Create Node接口
      tags:
      - Node相关接口
  '/node/metrics/:nodename/:':
    get:
      consumes:
      - application/json
      description: 获取Node信息
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        type: string
      produces:
      - application/json
      responses: {}
      security:
      - ApiKeyAuth: []
      summary: 获取Node接口
      tags:
      - Node相关接口
  '/node/node/:':
    get:
      consumes:
      - application/json
      description: 获取Node信息
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        type: string
      produces:
      - application/json
      responses: {}
      security:
      - ApiKeyAuth: []
      summary: 获取Node接口
      tags:
      - Node相关接口
  '/node/node/:nodename/:':
    get:
      consumes:
      - application/json
      description: 获取Node信息
      produces:
      - application/json
      responses: {}
      security:
      - ApiKeyAuth: []
      summary: 获取Node接口
      tags:
      - Node相关接口
  /pod/:
    post:
      consumes:
      - application/json
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        type: string
      produces:
      - application/json
      responses: {}
      security:
      - ApiKeyAuth: []
      summary: Create Pod接口
      tags:
      - Pod相关接口
  /pod/pod/:namespace/:name/:
    get:
      consumes:
      - application/json
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        type: string
      produces:
      - application/json
      responses: {}
      security:
      - ApiKeyAuth: []
      summary: Get Pod接口
      tags:
      - Pod相关接口
  /pod/pod/default/:
    get:
      consumes:
      - application/json
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        type: string
      produces:
      - application/json
      responses: {}
      security:
      - ApiKeyAuth: []
      summary: Get Pod接口
      tags:
      - Pod相关接口
  /router/rule/:
    get:
      consumes:
      - application/json
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        type: string
      produces:
      - application/json
      responses: {}
      security:
      - ApiKeyAuth: []
      summary: Get Rule 接口
      tags:
      - Rule  相关接口
    post:
      consumes:
      - application/json
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        type: string
      produces:
      - application/json
      responses: {}
      security:
      - ApiKeyAuth: []
      summary: Delete Rule 接口
      tags:
      - Rule  相关接口
  /router/rule/default/:name/:
    get:
      consumes:
      - application/json
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        type: string
      produces:
      - application/json
      responses: {}
      security:
      - ApiKeyAuth: []
      summary: Get Rule 接口
      tags:
      - Rule  相关接口
  /router/ruleendpoint/:
    get:
      consumes:
      - application/json
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        type: string
      produces:
      - application/json
      responses: {}
      security:
      - ApiKeyAuth: []
      summary: Get Rule Point 列表详情接口
      tags:
      - Rule Point 相关接口
    post:
      consumes:
      - application/json
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        type: string
      produces:
      - application/json
      responses: {}
      security:
      - ApiKeyAuth: []
      summary: Delete Rule Point详情接口
      tags:
      - Rule Point 相关接口
  /router/ruleendpoint/default/:name/:
    get:
      consumes:
      - application/json
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        type: string
      produces:
      - application/json
      responses: {}
      security:
      - ApiKeyAuth: []
      summary: Get Rule Point详情接口
      tags:
      - Rule Point 相关接口
  /svc_data/svc_data/:
    get:
      consumes:
      - application/json
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        type: string
      produces:
      - application/json
      responses: {}
      security:
      - ApiKeyAuth: []
      summary: Get SvcData 接口
      tags:
      - SvcData  相关接口
    post:
      consumes:
      - application/json
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        type: string
      produces:
      - application/json
      responses: {}
      security:
      - ApiKeyAuth: []
      summary: Post SvcData 接口
      tags:
      - SvcData  相关接口
swagger: "2.0"
